name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node_modules dependecies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Patch workers (fixes android build)
        run: sudo sysctl fs.inotify.max_user_instances=524288 && sudo sysctl fs.inotify.max_user_watches=524288 && sudo sysctl fs.inotify.max_queued_events=524288 && sudo sysctl -p

      - name: Run jettifier
        run: npx jetify

      - name: Setup java 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          architecture: x64 // (x64 or x86) - defaults to x64

      - name: Build android
        run: yarn android:build

      - name: Build web
        run: yarn web:build

#       - name: Setup wine for windows build
#         run: sudo apt-get install --no-install-recommends -y libopenjp2-tools && sudo apt install wine
        
      - name: Build desktop
        run: yarn desktop:build

      - name: Deploy to github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: web/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            android/app/build/outputs/apk/release/*.apk
            desktop/dist/*.dmg
            desktop/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
