name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    
    - name: Copy Dependecies from cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: yarn install
    
    - name: Setup java 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        architecture: x64 // (x64 or x86) - defaults to x64
    - name: Build android
      run: cd android && ./gradlew assembleRelease
